# Generated by Django 2.2.3 on 2019-08-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='done_todo_delay',
            field=models.IntegerField(default=48, verbose_name='Done Todo Delay'),
        ),
    ]
