# Generated by Django 2.2.3 on 2019-08-22 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('is_done', models.IntegerField(verbose_name='Is Done')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated At')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('status', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ToDo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
