# Generated by Django 2.2.4 on 2019-08-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_done',
            field=models.IntegerField(default=0, verbose_name='Is Done'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(default='ok', max_length=100),
        ),
    ]
